/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// API caching: NetworkFirst with 5min expiration
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 300,
      }),
    ],
  }),
);

// Handle Share Target POST — intercepts before page loads
self.addEventListener('fetch', (event: FetchEvent) => {
  const url = new URL(event.request.url);

  if (url.pathname === '/share-target' && event.request.method === 'POST') {
    event.respondWith(
      (async () => {
        const formData = await event.request.formData();
        const files = formData.getAll('file') as File[];

        // Store shared files in a temporary cache for the page to pick up
        const cache = await caches.open('share-target-cache');

        const fileKeys: string[] = [];
        for (let i = 0; i < files.length; i++) {
          const file = files[i];
          const key = `/share-target-file/${Date.now()}-${i}-${file.name}`;
          await cache.put(
            key,
            new Response(file, {
              headers: {
                'Content-Type': file.type,
                'X-File-Name': file.name,
                'X-File-Size': String(file.size),
              },
            }),
          );
          fileKeys.push(key);
        }

        // Redirect to the share target page with file keys
        const redirectUrl = new URL('/share-target', url.origin);
        redirectUrl.searchParams.set('files', fileKeys.join(','));

        return Response.redirect(redirectUrl.toString(), 303);
      })(),
    );
  }
});
